### ISSUE TITLE
xml报错

### ISSUE THREAD

**Issue by tesengiii** [YBYCS/SimpleCurriculum#1]
老哥好，下载代码复现了下，发现出现了错误
![image](https://user-images.githubusercontent.com/58262656/170410906-c0a62554-89ed-4c30-a94e-f106b27819cc.png)
显示少了文件或者找不到adio_button_select_color
老哥可以帮忙看看吗

**Comment by YBYCS** [comment]
android studio的锅 他没commit 导致少上传了这部分文件 现在已经重新提交了 你可以看看

**Comment by tesengiii** [comment]
谢老哥！ 可以了！
